multiplexer over scripts-start/signup-* for "add scripts; scripts"
Plus copy the attach -q thing from signup-web to -mail and -cron


Legacy-ID: 1087

diff --git a/bin/scripts b/bin/scripts
--- a/bin/scripts
+++ b/bin/scripts
@@ -1,4 +1,30 @@
 #!/bin/sh
 
+choices () {
+    echo 'scripts-start Begin a Quick-Start autoinstall (wikis, blogs, etc.)'
+    echo 'signup-web Enable the web scripts service'
+    echo 'signup-cron Enable the cron scripts service'
+    echo 'signup-mail Enable the mail scripts service'
+    echo 'signup-sql Sign up for a sql.mit.edu account'
+}
+
+nchoices=`choices | wc -l`
+
+echo
+echo "Welcome to scripts.mit.edu. Which service would you like to use?"
+echo
+choices | sed 's/^[^ ]* //' | cat -n
+echo
+printf "Please enter a number 1-%d: " "$nchoices"
+read num
+echo
+
 attach scripts 2>/dev/null
-. /mit/scripts/bin/scripts-start
+choice=`choices | sed -n "$num { s/ .*$//; p; }"`
+if [ -n "$choice" ]; then
+  . "/mit/scripts/bin$scriptsdev/$choice"
+else
+  echo "ERROR:"
+  echo "You must enter a number 1 through $nchoices."
+  exit 1
+fi
