Get the principal from klist instead of $USER.  Perform the admof check on all lockers (not just non-$USER lockers), and after checking that the locker exists.
Legacy-ID: 576

diff --git a/bin/signup-minimal b/bin/signup-minimal
--- a/bin/signup-minimal
+++ b/bin/signup-minimal
@@ -47,24 +47,22 @@ fi
 
 attach "$lname" 2>/dev/null
 
-if [ "$lname" != "$USER" ]; then
-  ans=`$WGET -q -O- "http://scripts.mit.edu/~signup/admof.php/$lname/$USER@ATHENA.MIT.EDU"`
-  if [ "$ans" != "yes" ]; then
-    echo
-    echo "ERROR:"
-    echo "It appears as though you are not an administrator of the locker <$lname>."
-    echo "Try running \"fs sa /mit/$lname $USER all\" and starting over."
-    echo "Contact scripts@mit.edu if you are unable to solve the problem."
-    exit 1
-  fi
-fi
-
-attach "$lname" 2>/dev/null
-
 if [ ! -d "/mit/$lname" ]; then
   echo
   echo "ERROR:"
   echo "Cannot find locker <$lname>."
+  exit 1
+fi
+
+principal=`klist -5 | sed -n 's/^Default principal: // p'`
+ans=`$WGET -q -O- "http://scripts.mit.edu/~signup/admof.php/$lname/$principal"`
+if [ "$ans" != "yes" ]; then
+  afsuser=`echo "$principal" | sed 's/@ATHENA.MIT.EDU$//'`
+  echo
+  echo "ERROR:"
+  echo "It appears as though you are not an administrator of the locker <$lname>."
+  echo "Try running \"fs sa /mit/$lname $afsuser all\" and starting over."
+  echo "Contact scripts@mit.edu if you are unable to solve the problem."
   exit 1
 fi
 
