Check for successful response from signup backend.
Legacy-ID: 502

diff --git a/bin/signup-minimal b/bin/signup-minimal
--- a/bin/signup-minimal
+++ b/bin/signup-minimal
@@ -54,7 +54,7 @@ if [ "$lname" != "$USER" ]; then
     echo "It appears as though you are not an administrator of the locker <$lname>."
     echo "Try running \"fs sa /mit/$lname $USER all\" and starting over."
     echo "Contact scripts@mit.edu if you are unable to solve the problem."
-    exit 0
+    exit 1
   fi
 fi
 
@@ -64,7 +64,7 @@ if [ ! -d "/mit/$lname" ]; then
   echo
   echo "ERROR:"
   echo "Cannot find locker <$lname>."
-  exit 0
+  exit 1
 fi
 
 ans=`fs la "/mit/$lname" | grep '^  system:a[nyuth]*user .*l'`
@@ -75,7 +75,7 @@ if [ -z "$ans" ]; then
   echo "You might want to run \"fs sa /mit/$lname system:anyuser l\""
   echo "(that's a lowercase L rather than a one) and then try again."
   echo "Contact scripts@mit.edu if you are unable to solve the problem."
-  exit 0
+  exit 1
 fi
 
 mkdir "/mit/$lname/.scripts-signup" 2>/dev/null
@@ -85,7 +85,7 @@ if [ ! -d "/mit/$lname/.scripts-signup" ]; then
   echo "ERROR:"
   echo "It appears as though you do not have write access to the locker <$lname>."
   echo "Contact scripts@mit.edu if you are unable to solve the problem."
-  exit 0
+  exit 1
 fi
 
 if type wget >/dev/null 2>/dev/null; then
@@ -94,8 +94,15 @@ else
   WGET="athrun gnu wget"
 fi
 
-$WGET -q -O/dev/null "http://scripts.mit.edu/~signup/$lname"
+ans=`$WGET -q -O- "http://scripts.mit.edu/~signup/$lname"`
 rmdir "/mit/$lname/.scripts-signup"
+
+if [ "$ans" != "done" ] && [ "$ans" != "username already taken" ]; then
+  echo "ERROR:"
+  echo "Signup reported the following error: \"$ans\"."
+  echo "Contact scripts@mit.edu for assistance."
+  exit 1
+fi
 
 success() {
   if [ "$initlname" -eq 0 ]; then
