dang shell scripting
Legacy-ID: 746

diff --git a/sbin/build-update b/sbin/build-update
--- a/sbin/build-update
+++ b/sbin/build-update
@@ -118,7 +118,10 @@ for package in $packages; do
 done
 
 [ "$found" = "yes" ] || die "error: Correct version not found."
-[ -e "$patchdir/extra/prepatch.sh" ] && (. "$patchdir/extra/prepatch.sh" || die "error: prepatch failed")
+
+if [ -e "$patchdir/extra/prepatch.sh" ]; then
+  . "$patchdir/extra/prepatch.sh" || die "error: prepatch failed"
+fi
 
 [ -s "$patchdir/oldfiles.absent" ] && (xargs -n1 test ! -e <"$patchdir/oldfiles.absent" || die "error: Conflicting files exist." )
 [ -s "$patchdir/check.md5" ] && (md5sum -c "$patchdir/check.md5" || die "error: MD5 check failed.")
