Make autoinstallers use ATHENA_USER instead of USER
Closes Trac #113

(Merge of r1510:1511 from branches/locker-dev to trunk, from adehnert)

Legacy-ID: 1513

diff --git a/deploy/bin/onathena b/deploy/bin/onathena
--- a/deploy/bin/onathena
+++ b/deploy/bin/onathena
@@ -262,7 +262,7 @@ if [ -f "/mit/$ailocker/deploy$scriptsdev/php.ini/$deploy" ]; then
 fi
 cd "$origdir"
 
-vsshrun "/mit/$ailocker/deploy$scriptsdev/bin/$deploy" "$sname" "$deploy" "$addrend" "$admin_username" "$requires_sql" "$scriptsdev" "$USER" || die "Unknown failure during configuration"
+vsshrun "/mit/$ailocker/deploy$scriptsdev/bin/$deploy" "$sname" "$deploy" "$addrend" "$admin_username" "$requires_sql" "$scriptsdev" "${ATHENA_USER:-$USER}" || die "Unknown failure during configuration"
 rm -f "$lroot/web_scripts/$addrend/.scripts-tmp"
 checkfailed
 
