mediawiki 1.11 installer + improvements to installer system
Legacy-ID: 456

diff --git a/deploy/bin/onathena b/deploy/bin/onathena
--- a/deploy/bin/onathena
+++ b/deploy/bin/onathena
@@ -7,6 +7,15 @@ checkfailed() {
   fi
 }
 
+die() {
+  echo "== INSTALLATION FAILED =="
+  echo "Sorry, the installation failed:"
+  echo "$@"
+  echo "Please contact scripts@mit.edu and provide a copy of the output of this installer."
+  exit 1
+}
+  
+
 sshrun() {
   athrun scripts scripts-ssh -l "$lname" "/mit/scripts/$@" 2>/dev/null
 }
@@ -29,13 +38,13 @@ checksqlpass() {
     fi
 }
 
-#if [ "$override" = "" ]; then
-#echo "The scripts.mit.edu automatic installers are currently unavailable."
-#echo "We hope to make them available again soon."
-#echo "If you would like us to notify you as soon as they are available again,"
-#echo "let us know by sending us an e-mail at scripts@mit.edu"
-#exit 
-#fi
+if [ "$override" = "" ]; then
+echo "The scripts.mit.edu automatic installers are currently unavailable."
+echo "We hope to make them available again soon."
+echo "If you would like us to notify you as soon as they are available again,"
+echo "let us know by sending us an e-mail at scripts@mit.edu"
+exit 
+fi
 
 echo 
 echo == Welcome to the scripts.mit.edu installer for $sname ==
@@ -215,7 +224,7 @@ if [ -f "/mit/scripts/deploy$scriptsdev/php.ini/$deploy" ]; then
 fi
 cd $origdir
 
-sshrun "deploy$scriptsdev/bin/$deploy '$sname' '$deploy' '$addrend' '$admin_username' '$requires_sql' '$scriptsdev' '$USER'"
+vsshrun "deploy$scriptsdev/bin/$deploy '$sname' '$deploy' '$addrend' '$admin_username' '$requires_sql' '$scriptsdev' '$USER'" || die "Unknown failure during configuration"
 rm -f /$lroot/web_scripts/$addrend/.scripts-tmp
 checkfailed
 
