Distinguish between scripts for scripts and scripts for autoinstallers.
Some pieces of the autoinstaller process are clearly tied to scripts
itself - e.g. scripts to get information from sql.mit.edu. Others are
clearly tied to the autoinstaller - e.g. the
/mit/scripts/deploy/bin/foo scripts.

Out-of-tree autoinstallers want to replace the latter, but not the
former.

For scripts that fall into the former category, explicitly call them
from /mit/scripts. For those that fall into the latter, call them from
/mit/$ailocker. New out-of-tree autoinstallers can define ailocker to
provide their own hooks.

Legacy-ID: 1494

diff --git a/deploy/bin/onathena b/deploy/bin/onathena
--- a/deploy/bin/onathena
+++ b/deploy/bin/onathena
@@ -2,6 +2,7 @@
 
 : ${aicontact:=scripts@mit.edu}
 : ${aimaintainer:=scripts.mit.edu}
+: ${ailocker=scripts}
 
 
 checkfailed() {
@@ -20,17 +21,18 @@ die() {
 }
 
 attach scripts
+attach "$ailocker"
 
 sshrun() {
-  /afs/athena.mit.edu/contrib/scripts/bin$scriptsdev/scripts-ssh "$lname" "/mit/scripts/$@" 2>/dev/null
+  /afs/athena.mit.edu/contrib/scripts/bin$scriptsdev/scripts-ssh "$lname" "$@" 2>/dev/null
 }
 
 vsshrun() {
-  /afs/athena.mit.edu/contrib/scripts/bin$scriptsdev/scripts-ssh "$lname" "/mit/scripts/$@"
+  /afs/athena.mit.edu/contrib/scripts/bin$scriptsdev/scripts-ssh "$lname" "$@"
 }
 
 checksqlpass() {
-    errors=`sshrun "sql/bin$scriptsdev/test-password"`
+    errors=`sshrun "/mit/scripts/sql/bin$scriptsdev/test-password"`
     if [ "$errors" != "" ]; then
         if [ "$1" -eq 1 ]; then
           rm -f "$lroot/.sql/my.cnf"
@@ -140,7 +142,7 @@ fs sa "$lroot/.sql" system:anyuser none
 fs sa "$lroot/.sql" system:authuser none
 
 if [ "$requires_sql" -eq 1 ]; then
-  sqlinfo=`sshrun "sql/bin$scriptsdev/get-password"`
+  sqlinfo=`sshrun "/mit/scripts/sql/bin$scriptsdev/get-password"`
   if [ "$sqlinfo" = "" ]; then
       echo 
       echo "You already have a MySQL account but you do not have a .my.cnf file."
@@ -206,7 +208,7 @@ if [ "$create_scripts_dir" -eq 1 ]; then
 fi
 
 if [ "$wizard" != "" ]; then
-  vsshrun "wizard/bin/wizard" "install" "$@" "$wizard" "$lroot/web_scripts/$addrend"
+  vsshrun "/mit/$ailocker/wizard/bin/wizard" "install" "$@" "$wizard" "$lroot/web_scripts/$addrend"
   exit 0
 fi
 
@@ -237,14 +239,14 @@ fi
 
 if [ "$prompt_password" -eq 1 ]; then
     stty -echo
-    sshrun "deploy$scriptsdev/bin/prompt-password" "$sname" "$deploy" "$addrend" "$admin_username"
+    sshrun "/mit/$ailocker/deploy$scriptsdev/bin/prompt-password" "$sname" "$deploy" "$addrend" "$admin_username"
     stty echo
 fi
 
 echo
 echo "Unpacking $sname... (this step might take several minutes)"
 # xavid: use p to keep the same permissions as in the file
-athrun scripts gtar zxpf "/mit/scripts/deploy$scriptsdev/$deploy.tar.gz"
+athrun scripts gtar zxpf "/mit/$ailocker/deploy$scriptsdev/$deploy.tar.gz"
 files=`athrun scripts gfind . -mindepth 1 -maxdepth 1 | grep -v .admin`
 numfiles=`echo "$files" | wc -l`
 if [ ! -z "$files" ]; then
@@ -253,14 +255,14 @@ if [ ! -z "$files" ]; then
         rmdir "$files"
     fi
 fi
-if [ -f "/mit/scripts/deploy$scriptsdev/php.ini/$deploy" ]; then
+if [ -f "/mit/$ailocker/deploy$scriptsdev/php.ini/$deploy" ]; then
         nodot=`echo "$lname" | sed "/\./s///"`;
-        sed -e "/SCRIPTS_USER/ s//$lname/" -e "/SCRIPTS_NODOT/ s//$nodot/" "/mit/scripts/deploy$scriptsdev/php.ini/$deploy" > php.ini
+        sed -e "/SCRIPTS_USER/ s//$lname/" -e "/SCRIPTS_NODOT/ s//$nodot/" "/mit/$ailocker/deploy$scriptsdev/php.ini/$deploy" > php.ini
         athrun scripts gfind . -mindepth 1 -type d -exec sh -c 'ln -sf "`echo "$1" | sed '\''s,[^/],,g; s,/,../,g'\''`php.ini" "$1/"' -- {} \;
 fi
 cd "$origdir"
 
-vsshrun "deploy$scriptsdev/bin/$deploy" "$sname" "$deploy" "$addrend" "$admin_username" "$requires_sql" "$scriptsdev" "$USER" || die "Unknown failure during configuration"
+vsshrun "/mit/$ailocker/deploy$scriptsdev/bin/$deploy" "$sname" "$deploy" "$addrend" "$admin_username" "$requires_sql" "$scriptsdev" "$USER" || die "Unknown failure during configuration"
 rm -f "$lroot/web_scripts/$addrend/.scripts-tmp"
 checkfailed
 
